#!/usr/bin/env python

import augeas
import sys
import json

path = sys.argv[1] if len(sys.argv) > 1 else 'etc/ssh/ssh_config.d/*'
key = sys.argv[2] if len(sys.argv) > 2 else 'VerifyHostKeyDNS'

a = augeas.Augeas()

have_key = False
matches = a.match(f"/files/{path}")
for m in matches:
    val = a.get(m + f"/{key}")
    if val == 'yes':
        have_key = True

obj = dict()
if not have_key:
    obj = [{"file": match} for match in matches]

json.dump(obj, sys.stdout, indent=2)
